name: DBT CI/CD - Run, Test, Docs, Notify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dbt-validate:
    name: Compile DBT Project
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dbt-labs/dbt-core:1.9.3
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dbt-snowflake
        run: pip install dbt-snowflake

      - name: dbt compile
        run: dbt compile --target dev
        env:
          DBT_PROFILES_DIR: .
          SNOW_PASSWORD: ${{ secrets.SNOW_PASSWORD }}

  dbt-run:
    name: Run & Test DBT (dev/prod)
    needs: dbt-validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, prod]
    container:
      image: ghcr.io/dbt-labs/dbt-core:1.9.3
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dbt-snowflake
        run: pip install dbt-snowflake

      - name: dbt run
        run: dbt run --target ${{ matrix.env }}
        env:
          DBT_PROFILES_DIR: .
          SNOW_PASSWORD: ${{ secrets.SNOW_PASSWORD }}

      - name: dbt test
        run: dbt test --target ${{ matrix.env }}
        env:
          SNOW_PASSWORD: ${{ secrets.SNOW_PASSWORD }}

     
  build-docs:
    name: Build DBT Docs (prod)
    needs: dbt-run
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dbt-labs/dbt-core:1.9.3
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dbt-snowflake
        run: pip install dbt-snowflake

      - name: Generate dbt docs
        run: dbt docs generate --target prod
        env:
          DBT_PROFILES_DIR: .
          SNOW_PASSWORD: ${{ secrets.SNOW_PASSWORD }}

      - name: Prepare docs directory
        run: |
          mkdir docs
          cp target/index.html docs/
          cp target/manifest.json docs/
          cp target/catalog.json docs/

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

  deploy-pages:
    name: Deploy DBT Docs to GitHub Pages
    needs: build-docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
